import Head from "next/head";
import { auth } from "../config/firebase";
import Login from "../components/Login";
import styles from "../styles/Home.module.css";
import { useAuthState } from "react-firebase-hooks/auth";
import ChatRoom from "../components/ChatRoom";
import { Center, Spinner } from "@chakra-ui/react"

export default function Home() {
	const [user, loading] = useAuthState(auth);
	
	if (loading) {
		return (
			<Center bg="gray.200" opacity="50%" width="100vw" height="100vh" zIndex={9999}>
				<Spinner/>
			</Center>
		)
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>Realtime Chat App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				{user ? <ChatRoom /> : <Login />}
			</main>
		</div>
	);
}
